### ISSUE TITLE
Bem bo'yicha yo'zish kerak

### ISSUE THREAD

**Issue by umarmuhandis** [umarmuhandis/uzAuto#22]
# BEM bo'yicha yozishga kelishgandikku

https://github.com/umarmuhandis/uzAuto/blob/7291951f1dde805cc7bb4964e64bc7c29597271e/index.html#L14

**Comment by Nurkhayot** [comment]
bo'ldi hal qilamiz

**Comment by umarmuhandis** [comment]
Success!
